services:
  backend:
    image: ghcr.io/vialab/wiktionaryviz-backend:latest
    build:
      context: ./backend
    pull_policy: always
    container_name: wiktionaryviz-backend
    ports:
      - '8000:8000'
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - WIKTIONARY_DATA_URL=${WIKTIONARY_DATA_URL}
      - SKIP_DOWNLOAD=${SKIP_DOWNLOAD}
    volumes:
      - wiktionary-data:/app/data
    command: ['uvicorn', 'main:app', '--host', '0.0.0.0', '--port', '8000']
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'python',
          '-c',
          "import urllib.request as u; u.urlopen('http://localhost:8000/').read()",
        ]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  wiktionary-data:
