name: "Node Setup with Cache"
description: "Setup Node.js with npm cache and install dependencies (ci if lockfile)."
inputs:
  node-version:
    description: "Node.js version"
    required: false
    default: "20"
  cache-dependency-path:
    description: "Path(s) to dependency lockfiles for cache key"
    required: false
    default: "package-lock.json"
runs:
  using: "composite"
  steps:
    - name: Use Node.js
      # TODO: Pin to a specific commit SHA
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        cache-dependency-path: ${{ inputs.cache-dependency-path }}

    - name: Install deps (ci if lockfile)
      shell: bash
      run: |
        if [ -f package-lock.json ]; then
          npm ci --prefer-offline --no-audit --progress=false
        else
          npm install --prefer-offline --no-audit --progress=false
        fi
