name: backend-docker

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-docker.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 20
    steps:
      - name: Checkout
        # TODO: Pin to a specific commit SHA
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Set up Docker Buildx
        # TODO: Pin to a specific commit SHA
        uses: docker/setup-buildx-action@v3

      # Optional: Log in to a registry (uncomment and set secrets to push image)
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        # TODO: Pin to a specific commit SHA
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false # set to true if you configure registry login
          cache-from: type=gha,scope=backend
          cache-to: type=gha,mode=max,scope=backend
          tags: |
            wiktionaryviz/backend:latest

      - name: Cache image as artifact (optional)
        if: ${{ false }}
        uses: actions/upload-artifact@v4
        with:
          name: backend-image-tar
          path: |
            # Example to save: docker save wiktionaryviz/backend:latest -o backend.tar
            # Implement saving in a prior step if desired
            backend.tar
