name: release-publish

on:
  release:
    types: [published]

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  backend-docker:
    name: Build backend image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout @ release tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Optional: Log in to a registry to push image tags for the release
      # - name: Log in to GitHub Container Registry
      #   if: ${{ secrets.GHCR_TOKEN != '' }}
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GHCR_TOKEN }}

      - name: Build backend image (no push)
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: |
            wiktionaryviz/backend:${{ github.event.release.tag_name }}
            wiktionaryviz/backend:latest

  pages:
    name: Build and deploy to gh-pages
    needs: backend-docker
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout @ release tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install

      - name: Build site with API base
        env:
          API_BACKEND: ${{ secrets.API_BACKEND }}
        run: npm run build

      - name: Deploy to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true
          commit-message: Deploy frontend (release) – ${{ github.event.release.tag_name }} / ${{ github.sha }}
