name: release-please

on:
  push:
    branches: [ main ]
    # Avoid infinite loops: ignore files updated by Release Please
    paths-ignore:
      - 'CHANGELOG.md'
      - 'backend/CHANGELOG.md'
      - '.release-please-manifest.json'
      - 'package.json'
      - 'package-lock.json'
      - 'version.txt'
      - 'backend/version.txt'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-please:
    runs-on: ubuntu-latest
    # Skip when the squash merge commit is the release commit to avoid re-opening PRs
    if: "!contains(github.event.head_commit.message, 'chore(main): release')"
    timeout-minutes: 10
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: .github/release-please-config.json
          manifest-file: .release-please-manifest.json
        
