name: release-please

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - 'package.json'
      - 'backend/**'
      - '.github/release-please-config.json'
      - '.github/workflows/release-please.yml'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: .github/release-please-config.json
          manifest-file: .release-please-manifest.json
